team_name_mapping = {
    "密爾瓦基公鹿": "MIL",
    "亞特蘭大老鷹": "ATL",
    "達拉斯獨行俠": "DAL",
    "洛杉磯湖人": "LAL",
    "紐奧良鵜鶘": "NO",
    "沙加緬度國王": "SAC",
    "聖安東尼奧馬刺": "SA",
    "華盛頓巫師": "WAS",
    "丹佛金塊": "DEN",
    "夏洛特黃蜂": "CHA",
    "金州勇士": "GS",
    "曼斐斯灰熊": "MEM",
    "洛杉磯快艇": "LAC",
    "奧克拉荷馬雷霆": "OKC",
    "底特律活塞": "DET",
    "紐約尼克": "NY",
    "克里夫蘭騎士": "CLE",
    "印第安那溜馬": "IND",
    "多倫多暴龍": "TOR",
    "休士頓火箭": "HOU",
    "波士頓塞爾提克": "BOS",
    "費城76人": "PHI",
    "奧蘭多魔術": "ORL",
    "鳳凰城太陽": "PHX",
    "猶他爵士": "UTA",
    "布魯克林籃網": "BKN",
    "波特蘭拓荒者": "POR",
    "邁阿密熱火": "MIA",
    "芝加哥公牛": "CHI",
    "明尼蘇達灰狼": "MIN",
}

host_timezone = {
    "MIL": 'America/Chicago',
    "ATL": 'America/New_York',
    "DAL": 'America/Chicago',
    "LAL": 'America/Los_Angeles',
    "NO": 'America/Barbados',
    "SAC": 'America/Los_Angeles',
    "SA": 'America/Santiago',
    "WAS": 'America/New_York',
    "DEN": 'America/Denver',
    "CHA": 'America/New_York',
    "GS": 'America/Los_Angeles',
    "MEM": 'America/Kentucky/Louisville',
    "LAC": 'America/Los_Angeles',
    "OKC": 'America/Chicago',
    "DET": 'America/Detroit',
    "NY": 'America/New_York',
    "CLE": 'America/New_York',
    "IND": 'America/New_York',
    "TOR": 'America/Toronto',
    "HOU": 'America/Chicago',
    "BOS": 'America/New_York',
    "PHI": 'America/New_York',
    "ORL": 'America/Chicago',
    "PHX": 'America/Phoenix',
    "UTA": 'America/Denver',
    "BKN": 'America/New_York',
    "POR": 'America/Los_Angeles',
    "MIA": 'America/New_York',
    "CHI": 'America/Chicago',
    "MIN": 'America/Chicago',
}

game_type_map = {"MLB": 1, "NPB": 2, "NBA": 3, "FOOTBALL": 4, "CPBL": 6, "WNBA": 7}
