# table name
game_data = 'game_data'
prediction_data = 'prediction_data'
game_judgement = 'game_judgement'
prediction_judgement = 'prediction_judgement'
prediction_judgement_summarize = 'prediction_judgement_summarize'

# game judgement
host_win_original = 'host_win_original'
host_win_point_spread_national = 'host_win_point_spread_national'
host_win_point_spread_local = 'host_win_point_spread_local'
over_total_point_national = 'over_total_point_national'
over_total_point_local = 'over_total_point_local'

# prediction judgement
national_point_spread_result = 'national_point_spread_result'
national_point_spread_population = 'national_point_spread_population'
national_point_spread_percentage = 'national_point_spread_percentage'

national_total_point_result = 'national_total_point_result'
national_total_point_population = 'national_total_point_population'
national_total_point_percentage = 'national_total_point_percentage'

local_point_spread_result = 'local_point_spread_result'
local_point_spread_population = 'local_point_spread_population'
local_point_spread_percentage = 'local_point_spread_percentage'

local_total_point_result = 'local_total_point_result'
local_total_point_population = 'local_total_point_population'
local_total_point_percentage = 'local_total_point_percentage'

local_original_result = 'local_original_result'
local_original_population = 'local_original_population'
local_original_percentage = 'local_original_percentage'

# column name of prediction judge summarize
win_ratio = 'win_ratio'
max_continuous_lose = 'max_continuous_lose'
number_of_valid_game = 'number_of_valid_game'
member_group = 'member_group'
national_point_spread_win_ratio = 'national_point_spread_win_ratio'
national_point_spread_max_continuous_lose = 'national_point_spread_max_continuous_lose'
national_point_spread_number_of_valid_game = 'national_point_spread_number_of_valid_game'
national_total_point_win_ratio = 'national_total_point_win_ratio'
national_total_point_max_continuous_lose = 'national_total_point_max_continuous_lose'
national_total_point_number_of_valid_game = 'national_total_point_number_of_valid_game'
local_point_spread_win_ratio = 'local_point_spread_win_ratio'
local_point_spread_max_continuous_lose = 'local_point_spread_max_continuous_lose'
local_point_spread_number_of_valid_game = 'local_point_spread_number_of_valid_game'
local_total_point_win_ratio = 'local_total_point_win_ratio'
local_total_point_max_continuous_lose = 'local_total_point_max_continuous_lose'
local_total_point_number_of_valid_game = 'local_total_point_number_of_valid_game'
local_original_win_ratio = 'local_original_win_ratio'
local_original_max_continuous_lose = 'local_original_max_continuous_lose'
local_original_number_of_valid_game = 'local_original_number_of_valid_game'

# column name of game_data
row_id = 'id'
game_date = 'game_date'
gamble_id = 'gamble_id'
# game_id = 'game_id'
game_type = 'game_type'
play_time = 'play_time'
am_pm = 'AM_PM'
host_id = 'host_id'
guest_id = 'guest_id'
host_score = 'host_score'
guest_score = 'guest_score'
national_host_point_spread = 'national_host_point_spread'
win_if_meet_spread_point = 'win_if_meet_spread_point'
response_ratio_if_hit_spread_point = 'response_ratio_if_hit_spread_point'
national_total_point_threshold = 'national_total_point_threshold'
local_host_point_spread = 'local_host_point_spread'
local_total_point_threshold = 'local_total_point_threshold'
local_host_point_spread_response_ratio = 'local_host_point_spread_response_ratio'
local_total_point_threshold_response_ratio = 'local_total_point_threshold_response_ratio'
local_origin_guest_response_ratio = 'local_origin_guest_response_ratio'
local_origin_host_response_ratio = 'local_origin_host_response_ratio'
guest = 'guest'
host = 'host'

# prediction
percentage_national_point_spread_guest = 'percentage_national_point_spread_guest'
percentage_national_point_spread_host = 'percentage_national_point_spread_host'
population_national_point_spread_guest = 'population_national_point_spread_guest'
population_national_point_spread_host = 'population_national_point_spread_host'

percentage_national_total_point_over = 'percentage_national_total_point_over'
percentage_national_total_point_under = 'percentage_national_total_point_under'
population_national_total_point_over = 'population_national_total_point_over'
population_national_total_point_under = 'population_national_total_point_under'

percentage_local_point_spread_guest = 'percentage_local_point_spread_guest'
percentage_local_point_spread_host = 'percentage_local_point_spread_host'
population_local_point_spread_guest = 'population_local_point_spread_guest'
population_local_point_spread_host = 'population_local_point_spread_host'

percentage_local_total_point_over = 'percentage_local_total_point_over'
percentage_local_total_point_under = 'percentage_local_total_point_under'
population_local_total_point_over = 'population_local_total_point_over'
population_local_total_point_under = 'population_local_total_point_under'

percentage_local_original_guest = 'percentage_local_original_guest'
percentage_local_original_host = 'percentage_local_original_host'
population_local_original_guest = 'population_local_original_guest'
population_local_original_host = 'population_local_original_host'
