name: release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: release
          uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: minor

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          push: true
          tags: allensyk/kaiji-crawler:${{ github.ref }}
      - name: Image digest
        run: |
        echo ${{ steps.docker_build.outputs.digest }}
        echo "release docker image allensyk/kaiji-crawler:${{ github.ref }}
